INSERT INTO Books (Title, AuthorFirstName, AuthorLastName, PublicationYear, Genre) VALUES
('To Kill a Mockingbird', 'Harper', 'Lee', 1960, 'Fiction'),
('1984', 'George', 'Orwell', 1949, 'Dystopian'),
('Pride and Prejudice', 'Jane', 'Austen', 1813, 'Romance'),
('The Great Gatsby', 'F. Scott', 'Fitzgerald', 1925, 'Classic'),
('Moby Dick', 'Herman', 'Melville', 1851, 'Adventure'),
('War and Peace', 'Leo', 'Tolstoy', 1869, 'Historical'),
('The Catcher in the Rye', 'J.D.', 'Salinger', 1951, 'Fiction'),
('The Hobbit', 'J.R.R.', 'Tolkien', 1937, 'Fantasy'),
('Harry Potter and the Sorcerer\'s Stone', 'J.K.', 'Rowling', 1997, 'Fantasy'),
('Crime and Punishment', 'Fyodor', 'Dostoevsky', 1866, 'Psychological'),
('Brave New World', 'Aldous', 'Huxley', 1932, 'Science Fiction'),
('Jane Eyre', 'Charlotte', 'Brontë', 1847, 'Romance'),
('The Lord of the Rings', 'J.R.R.', 'Tolkien', 1954, 'Fantasy'),
('Fahrenheit 451', 'Ray', 'Bradbury', 1953, 'Dystopian'),
('The Alchemist', 'Paulo', 'Coelho', 1988, 'Adventure'),
('The Road', 'Cormac', 'McCarthy', 2006, 'Post-Apocalyptic'),
('Of Mice and Men', 'John', 'Steinbeck', 1937, 'Fiction'),
('The Picture of Dorian Gray', 'Oscar', 'Wilde', 1890, 'Gothic'),
('Wuthering Heights', 'Emily', 'Brontë', 1847, 'Romance'),
('Frankenstein', 'Mary', 'Shelley', 1818, 'Horror'),
('Dracula', 'Bram', 'Stoker', 1897, 'Horror'),
('The Shining', 'Stephen', 'King', 1977, 'Horror'),
('A Game of Thrones', 'George R.R.', 'Martin', 1996, 'Fantasy'),
('Anna Karenina', 'Leo', 'Tolstoy', 1877, 'Romance'),
('The Grapes of Wrath', 'John', 'Steinbeck', 1939, 'Historical'),
('Slaughterhouse-Five', 'Kurt', 'Vonnegut', 1969, 'Science Fiction'),
('The Scarlet Letter', 'Nathaniel', 'Hawthorne', 1850, 'Classic'),
('The Kite Runner', 'Khaled', 'Hosseini', 2003, 'Drama'),
('Life of Pi', 'Yann', 'Martel', 2001, 'Adventure'),
('The Fault in Our Stars', 'John', 'Green', 2012, 'Romance'),
('Percy Jackson and the Olympians', 'Rick', 'Riordan', 2005, 'Fantasy'),
('The Hunger Games', 'Suzanne', 'Collins', 2008, 'Dystopian'),
('Dune', 'Frank', 'Herbert', 1965, 'Science Fiction'),
('The Name of the Wind', 'Patrick', 'Rothfuss', 2007, 'Fantasy'),
('The Handmaid\'s Tale', 'Margaret', 'Atwood', 1985, 'Dystopian');