-- Insert demo data
INSERT INTO Books (Title, Author, PublicationYear, Genre) VALUES
('The Silent Forest', 'Emily Stone', 2010, 'Mystery'),
('Journey Through Time', 'Michael Rivers', 2015, 'Science Fiction'),
('Whispers of the Heart', 'Sarah Collins', 2008, 'Romance'),
('Echoes of Eternity', 'David Mitchell', 2020, 'Fantasy'),
('The Last Horizon', 'Laura Palmer', 2012, 'Adventure'),
('Shadows in the Mist', 'James Everett', 2005, 'Horror'),
('Beyond the Stars', 'Olivia Turner', 2018, 'Science Fiction'),
('The Forgotten Path', 'Daniel Brooks', 2003, 'Historical Fiction'),
('Rise of the Phoenix', 'Sophia Bennett', 2021, 'Fantasy'),
('Under the Crimson Sky', 'Ethan Walker', 2016, 'Action'),
('Secrets of the Ancients', 'Isabella Reed', 2009, 'Thriller'),
('The Golden Compass', 'Liam Harris', 1995, 'Fantasy'),
('Tides of Change', 'Ava Campbell', 2014, 'Drama'),
('Labyrinth of Souls', 'Noah Murphy', 2011, 'Mystery'),
('Celestial Dreams', 'Mia Foster', 2019, 'Romance'),
('The Iron Fortress', 'Lucas Hughes', 2007, 'Fantasy'),
('Veil of Illusions', 'Amelia Russell', 2022, 'Fantasy'),
('The Hidden Realm', 'Benjamin Cox', 2006, 'Adventure'),
('Starlight Sonata', 'Charlotte Perry', 2017, 'Romance'),
('The Darkened Tower', 'Henry Powell', 2004, 'Horror'),
('Fragments of Time', 'Ella Patterson', 2013, 'Science Fiction'),
('Embers of War', 'Alexander Long', 2018, 'Historical Fiction'),
('The Lost Expedition', 'Grace Butler', 2010, 'Adventure'),
('Midnight Serenade', 'William Simmons', 2015, 'Romance'),
('The Obsidian Blade', 'Lily Foster', 2020, 'Fantasy'),
('Whirlwind Journey', 'Jack Murphy', 2008, 'Action'),
('The Enchanted Grove', 'Zoe Barnes', 2012, 'Fantasy'),
('Crimson Shadows', 'Sebastian Hughes', 2005, 'Thriller'),
('The Sapphire Key', 'Chloe Coleman', 2016, 'Mystery'),
('Moonlit Sonata', 'Mason Ward', 2011, 'Romance'),
('The Celestial Navigator', 'Abigail Jenkins', 2019, 'Science Fiction'),
('Rising Tide', 'Elijah Bennett', 2021, 'Drama'),
('The Emerald Isle', 'Harper Ross', 2003, 'Adventure'),
('Silent Whispers', 'Daniel Lee', 2007, 'Horror'),
('The Radiant Dawn', 'Avery Foster', 2014, 'Fantasy'),
('Twilight Veil', 'Matthew Carter', 2018, 'Mystery'),
('The Azure Horizon', 'Scarlett Bell', 2010, 'Science Fiction'),
('Echoes of the Past', 'Ryan Morgan', 2015, 'Historical Fiction'),
('The Obsidian Crown', 'Layla Adams', 2022, 'Fantasy'),
('Mystic River', 'Nathan Brooks', 2009, 'Adventure'),
('The Forgotten Kingdom', 'Lily Simmons', 2013, 'Fantasy'),
('Whispers of the Night', 'Isaac Powell', 2006, 'Horror'),
('The Golden Gate', 'Victoria Hayes', 2017, 'Drama'),
('Shadowed Memories', 'Gabriel Turner', 2019, 'Thriller'),
('The Twilight Prophecy', 'Ella Richardson', 2020, 'Fantasy'),
('Beyond the Veil', 'Caleb Hughes', 2011, 'Mystery'),
('The Lost Symphony', 'Aurora Coleman', 2016, 'Romance'),
('Shores of Infinity', 'Caden Morris', 2004, 'Science Fiction'),
('1984', 'George Orwell', 1949, 'Dystopian'),
('To Kill a Mockingbird', 'Harper Lee', 1960, 'Classic'),
('The Great Gatsby', 'F. Scott Fitzgerald', 1925, 'Classic');
